---
################################################################################
# Nested YAML with Tasks - By F0otsh0T / Johnny C
################################################################################
# JUNOS Install Config from Backup:
#   - 05-JUNOSInstallConfig: Upload and Apply Config
################################################################################
#  tasks:
##########
  - name: 05-CheckNetConfConnectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 300

################################################################################
# Juniper.junos_install_config from previous Config backup
################################################################################
  - name: 05-JUNOSInstallConfig
    junos_install_config:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      user: "{{ JUNOS_USERNAME }}"
      ssh_private_key_file: "{{ SSH_PRIVATE_KEY_FILE }}"
#      passwd: "{{ JUNOS_PASSWORD }}"
      file: "{{ CFG_DIR }}/{{ inventory_hostname }}.conf"
      overwrite: yes
      logfile: "{{ LOG_DIR }}/05.log.junos_install_cfg.{{ inventory_hostname }}"
    register: JUNOSINSTALLCONFIG
##########
  - name: 05-DebugJUNOSINSTALLCONFIG
    debug:
      msg: "{{ JUNOSINSTALLCONFIG }}"
##########
  - name: 05-CopyDebugJUNOSINSTALLCONFIG
    copy:
      content: "{{ JUNOSINSTALLCONFIG }}"
      dest: "{{ DEBUG_DIR }}/05.debug.junos_install_config.{{ inventory_hostname }}"
