---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# OpenStack VMI/Port Up (Contrail 2.x Environments):
#   - SetVMILeft-admin_state_up-true: Enable LEFT
#   - SetVMIRight-admin_state_up-true: Enable RIGHT
################################################################################
#  tasks:

################################################################################
# Set Variables
################################################################################
  - name: SetVMIFact
    set_fact:
      TENANT: "{{ OS_PROJECT_NAME }}"
      VMI: "{{ os_vmi_c2x }}"
    register: SETVMIFACT
##########
  - name: DebugSETVMIFACT
    debug:
      msg: "{{ SETVMIFACT }}"
##########
  - name: CopyDebugSETVMIFACT
    copy:
      content: "{{ SETVMIFACT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetfact.default-domain__{{ TENANT }}__{{ VMI }}"

################################################################################
# Set VMI/OS::Neutron::Port Up - LEFT Interface
################################################################################
  - name: SetVMILeft-admin_state_up-true
    os_port:
      state: present
      auth:
        auth_url: "{{ OS_AUTH_URL }}"
        username: "{{ OS_USERNAME }}"
        password: "{{ OS_PASSWORD }}"
        project_name: "{{ OS_PROJECT_NAME }}"
########## This name could be whatever naming convention you used for your VMI/OS::Neutron::Port
      name: "default-domain__{{ TENANT }}__{{ VMI }}__left__2"
      admin_state_up: true
    register: SETVMI1UPLEFT
    until: SETVMI1UPLEFT.port.admin_state_up == true
    retries: 5
    delay: 30
##########
  - name: DebugSETVMI1UPLEFT
    debug:
      msg: "{{ SETVMI1UPLEFT }}"
##########
  - name: CopyDebugSETVMI1UPLEFT
    copy:
      content: "{{ SETVMI1UPLEFT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"

################################################################################
# Verify VMI/OS::Neutron::Port is Correct - LEFT Interface
################################################################################
  - name: WaitForvSRXVMI1
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"
#      search_regex: '"name": "default-domain__{{ TENANT }}__{{ VMI }}__left__2"'
      search_regex: '"name": ".+?(?=__)__{{ VMI }}__left__2"'
    register: WAITFORVSRXVMI1
##########
  - name: DebugWAITFORVSRXVMI1
    debug:
      msg: "{{ WAITFORVSRXVMI1 }}"

################################################################################
# Verify VMI/OS::Neutron::Port is Up - LEFT Interface
################################################################################
  - name: WaitForvSRXVMI1StatusUp
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"
      search_regex: '"admin_state_up": true'
    register: WAITFORVSRXVMI1UP
##########
  - name: DebugWAITFORVSRXVMI1UP
    debug:
      msg: "{{ WAITFORVSRXVMI1UP }}"

################################################################################
# Set VMI/OS::Neutron::Port Up - RIGHT Interface
################################################################################
  - name: SetVMIRight-admin_state_up-true
    os_port:
      state: present
      auth:
        auth_url: "{{ OS_AUTH_URL }}"
        username: "{{ OS_USERNAME }}"
        password: "{{ OS_PASSWORD }}"
        project_name: "{{ OS_PROJECT_NAME }}"
########## This name could be whatever naming convention you used for your VMI/OS::Neutron::Port
      name: "default-domain__{{ TENANT }}__{{ VMI }}__right__3"
      admin_state_up: true
    register: SETVMI2UPRIGHT
    until: SETVMI2UPRIGHT.port.admin_state_up == true
    retries: 5
    delay: 30
##########
  - name: DebugSETVMI2UPRIGHT
    debug:
      msg: "{{ SETVMI2UPRIGHT }}"
##########
  - name: CopyDebugSETVMI2UPRIGHT
    copy:
      content: "{{ SETVMI2UPRIGHT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"

################################################################################
# Verify VMI/OS::Neutron::Port is Correct - RIGHT Interface
################################################################################
  - name: WaitForvSRXVMI2
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"
#      search_regex: '"name": "default-domain__{{ TENANT }}__{{ VMI }}__right__3"'
      search_regex: '"name": ".+?(?=__)__{{ VMI }}__right__3"'
    register: WAITFORVSRXVMI2
##########
  - name: DebugWAITFORVSRXVMI2
    debug:
      msg: "{{ WAITFORVSRXVMI2 }}"

################################################################################
# Verify VMI/OS::Neutron::Port is Up - RIGHT Interface
################################################################################
  - name: WaitForvSRXVMI2StatusUp
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_up.c2x-vmisetupright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"
      search_regex: '"admin_state_up": true'
    register: WAITFORVSRXVMI2UP
##########
  - name: DebugWAITFORVSRXVMI2UP
    debug:
      msg: "{{ WAITFORVSRXVMI2UP }}"
