---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# JUNOS Tasks:
#   - JUNOSPostCheckFacts: Get Facts JSON
#   - JUNOSPostCheckInterfaces: Get Interface Info
#   - JUNOSPostCheckConfig: Get Final Post Upgrade Config
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity
################################################################################
  - name: CheckNetConfConnectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 60

################################################################################
# Post Update Check Facts & Record Output
################################################################################
  - name: JUNOSPostCheckFacts
    junos_get_facts:
      host: "{{ ansible_host }}"
      user: "{{ JUNOS_USERNAME }}"
      ssh_private_key_file: "{{ SSH_PRIVATE_KEY_FILE }}"
#      passwd: "{{ JUNOS_PASSWORD }}"
      port: "{{ NETCONF_PORT }}"
      logfile: "{{ LOG_DIR }}/log.junos-post_get_facts.{{ inventory_hostname }}"
      savedir: "{{ OUTPUT_DIR }}"
    register: SRXINFO
################################################################################
  - name: DebugSRXINFO
    debug:
      msg: "{{ SRXINFO }}"
################################################################################
  - name: CopyDebugSRXINFO
    copy:
      content: "{{ SRXINFO }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-post_get_facts.{{ inventory_hostname }}"
################################################################################
  - name: DebugSRXINFO.facts
    debug:
      msg: "{{ SRXINFO.facts }}"
################################################################################
  - name: CopyDebugSRXINFO.facts
    copy:
      content: "{{ SRXINFO.facts }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-post_get_facts.{{ inventory_hostname }}"

################################################################################
# Post Update Check Interfaces & Record Output
################################################################################
  - name: JUNOSPostCheckInterfaces
    junos_cli:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      user: "{{ JUNOS_USERNAME }}"
      ssh_private_key_file: "{{ SSH_PRIVATE_KEY_FILE }}"
#      passwd: "{{ JUNOS_PASSWORD }}"
      cli: "show interfaces terse"
      dest: "{{ OUTPUT_DIR }}/out.junos-post_check_interfaces.{{ inventory_hostname }}"
      logfile: "{{ LOG_DIR }}/log.junos-post_check_interfaces.{{ inventory_hostname }}"
    register: POSTCHECKINTERFACES
################################################################################
  - name: DebugPOSTCHECKINTERFACES
    debug:
      msg: "{{ POSTCHECKINTERFACES }}"
################################################################################
  - name: CopyDebugPOSTCHECKINTERFACES
    copy:
      content: "{{ POSTCHECKINTERFACES }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-post_check_interfaces.{{ inventory_hostname }}"

################################################################################
# Post Update Activity Check Configuration & Record Output
################################################################################
  - name: JUNOSGetConfig
    junos_get_config:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      user: "{{ JUNOS_USERNAME }}"
      ssh_private_key_file: "{{ SSH_PRIVATE_KEY_FILE }}"
#      passwd: "{{ JUNOS_PASSWORD }}"
      dest: "{{ CFG_DIR }}/{{ inventory_hostname }}.post.conf"
      logfile: "{{ LOG_DIR }}/log.junos-post_get_config.{{ inventory_hostname }}"
    register: GETCONFIG
##########
  - name: DebugGETCONFIG
    debug:
      msg: "{{ GETCONFIG }}"
##########
  - name: CopyDebugPRETASKGETCONFIG
    copy:
      content: "{{ GETCONFIG }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-post_get_config.{{ inventory_hostname }}"
