---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# -JUNOS Tasks:
#   - JUNOSDeleteAIS: Delete AIS Scripts
#   - JUNOSDeleteAISConfig: Delete AIS Config
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity
################################################################################
  - name: CheckNetConfConnectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 60

################################################################################
# Delete vSRX AIS Scripts from vSRX
################################################################################
  - name: JUNOSDeleteAIS
    junos_command:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      username: "{{ JUNOS_USERNAME }}"
      ssh_keyfile: "{{ SSH_PRIVATE_KEY_FILE }}"
#      password: "{{ JUNOS_PASSWORD }}"
      commands:
        - "request system scripts delete"
#        - "show configuration | no-more"
#      wait_for:
#        - result[0] contains jais
#        - result[1] contains version
      timeout: 90
    register: DELETEAIS
######################
    ignore_errors: yes
######################
##########
  - name: DebugDELETEAIS
    debug:
      msg: "{{ DELETEAIS }}"
##########
  - name: CopyDebugDELETEAIS
    copy:
      content: "{{ DELETEAIS }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-delete_ais.{{ inventory_hostname }}"

################################################################################
# Delete AIS References from vSRX Config
################################################################################
  - name: JUNOSDeleteAISConfig
    junos_config:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      username: "{{ JUNOS_USERNAME }}"
      ssh_keyfile: "{{ SSH_PRIVATE_KEY_FILE }}"
#      password: "{{ JUNOS_PASSWORD }}"
      lines:
        - "delete groups juniper-ais"
        - "delete apply-groups"
      timeout: 90
    register: DELETEAISCONFIG
######################
    ignore_errors: yes
######################
##########
  - name: DebugDELETEAISCONFIG
    debug:
      msg: "{{ DELETEAISCONFIG }}"
##########
  - name: CopyDebugDELETEAISCONFIG
    copy:
      content: "{{ DELETEAISCONFIG }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-delete_ais-config.{{ inventory_hostname }}"
