---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# JUNOS Tasks:
#   - JUNOSInstallConfig: Upload and Apply Config
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity
################################################################################
  - name: CheckNetConfConnectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 60

################################################################################
# Juniper.junos_install_config from previous Config backup
################################################################################
  - name: JUNOSInstallConfig
    junos_install_config:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      user: "{{ JUNOS_USERNAME }}"
      ssh_private_key_file: "{{ SSH_PRIVATE_KEY_FILE }}"
#      passwd: "{{ JUNOS_PASSWORD }}"
      file: "{{ CFG_DIR }}/{{ inventory_hostname }}.conf"
      overwrite: yes
      logfile: "{{ LOG_DIR }}/log.junos-install_config.{{ inventory_hostname }}"
    register: JUNOSINSTALLCONFIG
##########
  - name: DebugJUNOSINSTALLCONFIG
    debug:
      msg: "{{ JUNOSINSTALLCONFIG }}"
##########
  - name: CopyDebugJUNOSINSTALLCONFIG
    copy:
      content: "{{ JUNOSINSTALLCONFIG }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-install_config.{{ inventory_hostname }}"
