---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# JUNOS Tasks:
#   - JUNOSDisableSIInterfaces: Disable LEFT & RIGHT Interfaces
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity
################################################################################
  - name: CheckNetConfConnectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 60

################################################################################
# Disable ServiceInstance Interfaces
################################################################################
  - name: JUNOSDisableSIInterfaces
    junos_config:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      username: "{{ JUNOS_USERNAME }}"
      ssh_keyfile: "{{ SSH_PRIVATE_KEY_FILE }}"
#      password: "{{ JUNOS_PASSWORD }}"
      lines:
        - "set interfaces ge-0/0/0 disable"
        - "set interfaces ge-0/0/1 disable"
      timeout: 90
    register: DisableSIInterfaces
######################
    ignore_errors: yes
######################
##########
  - name: DebugDisableSIInterfaces
    debug:
      msg: "{{ DisableSIInterfaces }}"
##########
  - name: CopyDebugPRETASKAISCONFIGDELETE
    copy:
      content: "{{ DisableSIInterfaces }}"
      dest: "{{ DEBUG_DIR }}/deb.junos-disable_si_interfaces.{{ inventory_hostname }}"
