---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# OpenStack VMI/Port Down (Contrail 2.x Environments):
#   - SetVMILeft-admin_state_up-false: Disable LEFT
#   - SetVMIRight-admin_state_up-false: Disable RIGHT
################################################################################
#  tasks:

################################################################################
# Set Variables
################################################################################
  - name: SetFact
    set_fact:
      TENANT: "{{ OS_PROJECT_NAME }}"
      VMI: "{{ os_vmi_c2x }}"
    register: SETVMIFACT
##########
  - name: DebugSETVMIFACT
    debug:
      msg: "{{ SETVMIFACT }}"
##########
  - name: CopyDebugSETVMIFACT
    copy:
      content: "{{ SETVMIFACT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetfact.default-domain__{{ TENANT }}__{{ VMI }}"

################################################################################
# Set VMI/OS::Neutron::Port Down - LEFT Interface
################################################################################
  - name: SetVMILeft-admin_state_up-false
    os_port:
      state: present
      auth:
        auth_url: "{{ OS_AUTH_URL }}"
        username: "{{ OS_USERNAME }}"
        password: "{{ OS_PASSWORD }}"
        project_name: "{{ OS_PROJECT_NAME }}"
########## This name could be whatever naming convention you used for your VMI/OS::Neutron::Port
      name: "default-domain__{{ TENANT }}__{{ VMI }}__left__2"
      admin_state_up: false
    register: SETVMI1DOWNLEFT
    until: SETVMI1DOWNLEFT.port.admin_state_up == false
    retries: 3
    delay: 10
##########
  - name: DebugSETVMI1DOWNLEFT
    debug:
      msg: "{{ SETVMI1DOWNLEFT }}"
##########
  - name: CopyDebugSETVMI1DOWNLEFT
    copy:
      content: "{{ SETVMI1DOWNLEFT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"

################################################################################
# Verify VMI/OS::Neutron::Port is Correct - LEFT Interface
################################################################################
  - name: WaitForvSRXVMI1
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"
#      search_regex: '"name": "default-domain__{{ TENANT }}__{{ VMI }}__left__2"'
      search_regex: '"name": ".+?(?=__)__{{ VMI }}__left__2"'
    register: WAITFORVSRXVMI1
##########
  - name: DebugWAITFORVSRXVMI1
    debug:
      msg: "{{ WAITFORVSRXVMI1 }}"

################################################################################
# Verify VMI/OS::Neutron::Port is Down - LEFT Interface
################################################################################
  - name: WaitForvSRXVMI1StatusDown
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownleft.default-domain__{{ TENANT }}__{{ VMI }}__left__2"
      search_regex: '"admin_state_up": false'
    register: WAITFORVSRXVMI1DOWN
##########
  - name: DebugWAITFORVSRXVMI1DOWN
    debug:
      msg: "{{ WAITFORVSRXVMI1DOWN }}"

################################################################################
# Set VMI/OS::Neutron::Port Down - RIGHT Interface
################################################################################
  - name: SetVMIRight-admin_state_up-false
    os_port:
      state: present
      auth:
        auth_url: "{{ OS_AUTH_URL }}"
        username: "{{ OS_USERNAME }}"
        password: "{{ OS_PASSWORD }}"
        project_name: "{{ OS_PROJECT_NAME }}"
########## This name could be whatever naming convention you used for your VMI/OS::Neutron::Port
      name: "default-domain__{{ TENANT }}__{{ VMI }}__right__3"
      admin_state_up: false
    register: SETVMI2DOWNRIGHT
    until: SETVMI2DOWNRIGHT.port.admin_state_up == false
    retries: 3
    delay: 10
##########
  - name: DebugSETVMI2DOWNRIGHT
    debug:
      msg: "{{ SETVMI2DOWNRIGHT }}"
##########
  - name: CopyDebugSETVMI2DOWNRIGHT
    copy:
      content: "{{ SETVMI2DOWNRIGHT }}"
      dest: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"

################################################################################
# Verify VMI/OS::Neutron::Port is Correct - RIGHT Interface
################################################################################
  - name: WaitForvSRXVMI2
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"
#      search_regex: '"name": "default-domain__{{ TENANT }}__{{ VMI }}__right__3"'
      search_regex: '"name": ".+?(?=__)__{{ VMI }}__right__3"'
    register: WAITFORVSRXVMI2
##########
  - name: DebugWAITFORVSRXVMI2
    debug:
      msg: "{{ WAITFORVSRXVMI2 }}"

################################################################################
# Verify VMI/OS::Neutron::Port is Down - RIGHT Interface
################################################################################
  - name: WaitForvSRXVMI2StatusDown
    wait_for:
      path: "{{ DEBUG_DIR }}/deb.os-vmi_down.c2x-vmisetdownright.default-domain__{{ TENANT }}__{{ VMI }}__right__3"
      search_regex: '"admin_state_up": false'
    register: WAITFORVSRXVMI2DOWN
##########
  - name: DebugWAITFORVSRXVMI2DOWN
    debug:
      msg: "{{ WAITFORVSRXVMI2DOWN }}"
