---
################################################################################
# Nested YAML with Tasks - By F0otsh0T
################################################################################
# GALAXY Tasks:
#   - CheckNetConfConnectivity30: Check Connectivity - 30 Seconds
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity - 30 Seconds
################################################################################
  - name: CheckNetConfConnectivity30
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ NETCONF_PORT }}"
      timeout: 30
